apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: grpc
  name: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc
  template:
    metadata:
      labels:
        run: grpc
    spec:
      containers:
      - image: eduardoarodrigues/basic:grpc-1.3.jar
        name: grpc
        ports:
        - containerPort: 8080
