management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health-check
    info:
      enabled: false
  security:
    enabled: false
  endpoint.health.show-details: always
